# URL de connexion à la base de données PostgreSQL
spring.application.name=gestioncourrier
server.port=8089
spring.datasource.url=jdbc:postgresql://localhost:5432/CourriersBD

# Identifiants de connexion 
spring.datasource.username=postgres
spring.datasource.password=lavendave585

# Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Activation Des logs de validation Spring
server.error.include-message=always
server.error.include-binding-errors=always

#Pour la Date 

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd

# Désactive la conversion automatique des noms
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl